version: "2"
checks:
  argument-count:
    enabled: true
    config:
      threshold: 4
  complex-logic:
    enabled: true
    config:
      threshold: 4
  file-lines:
    enabled: true
    config:
      threshold: 250
  method-complexity:
    enabled: true
    config:
      threshold: 10
  method-count:
    enabled: true
    config:
      threshold: 20
  method-lines:
    enabled: true
    config:
      threshold: 25
  nested-control-flow:
    enabled: true
    config:
      threshold: 4
  return-statements:
    enabled: true
    config:
      threshold: 4
  similar-code:
    enabled: true
    config:
      threshold: 28 # higher threshold to be less annoying with boilerplate
  identical-code:
    enabled: true
    config:
      threshold: 28
plugins:
  eslint:
    enabled: true
    channel: "eslint-8"
  duplication:
    enabled: true
    config:
      languages:
        - javascript
        - typescript
  fixme:
    enabled: true
exclude_patterns:
  - "node_modules/"
  - "dist/"
  - "build/"
  - "coverage/"
  - "playwright-report/"
  - "**/*.spec.js"
  - "**/*.spec.ts"
  - "**/*.spec.tsx"
  - "**/*.test.js"
  - "**/*.test.ts"
  - "**/*.test.tsx"
